
server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academiadigital?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: mariaaugusta
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace